components:
  schemas:
    Product:
      type: object
      required:
        - description
        - price
        - quantity
      properties:
        description:
          type: string
          description: Description from product
        price:
          type: number
          description: Price from product
        quantity:
          type: number
          description: Quantity from product
      example:
        description: Sweet Candy 7Bello
        price: 0.50
        quantity: 100
    ProductCreatedResponse:
      allOf:
        - $ref: "#components/schemas/Product"
        - type: object
          required:
            - id
          properties:
            id:
              type: number
              description: The Indentificador from the Product saved in Data Base
          example:
            id: 1
            description: Sweet Candy 7Belo
            price: 0.50
            quantity: 100
    ProductCreationFailResponse:
      type: object
      properties:
        errorMessages:
          type: array
          items:
            type: string
          example:
            [
              "Description cannot be empty",
              "Price cannot be empty",
              "Quantity cannot be empty"
            ]