paths:
  /products:
    post:
      summary: Cria um novo produto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "201":
          description: Produto cadastrado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Product registered
        "400":
          description: O objeto Produto recebido é inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Invalid inputs

  /products/{id}:
    get:
      summary: Obtém um produto pelo ID
      tags:
        - Products
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID do produto
      responses:
        "200":
          description: Produto encontrado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Produto não encontrado

  /products/description/{description}:
    get:
      summary: Obtém produtos por descrição
      tags:
        - Products
      parameters:
        - in: path
          name: description
          required: true
          schema:
            type: string
          description: Descrição do produto
      responses:
        "200":
          description: Produtos encontrados com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
